#pragma once

#include <assert.h>
#include <gamemechanics.h>
#include <gamephase.h>
#include <basedeck.h>
#include "../resetfns.h"

int rhinocorn_tests(void);
int extremely_fertile_unicorn_tests(void);
int magical_kittencorn_tests(void);
int stabby_the_unicorn_tests(void);
int puppicorn_tests(void);
int rainbow_unicorn_tests(void);
int zombie_unicorn_tests(void);
int extremely_destructive_unicorn_tests(void);
int chainsaw_unicorn_tests(void);
int llamacorn_tests(void);
int americorn_tests(void);
int ginormous_unicorn_tests(void);
int seductive_unicorn_tests(void);
int angel_unicorn_tests(void);
int queen_bee_unicorn_tests(void);
int greedy_flying_unicorn_tests(void);
int annoying_flying_unicorn_tests(void);
int magical_flying_unicorn_tests(void);
int swift_flying_unicorn_tests(void);
int majestic_flying_unicorn_tests(void);
int unicorn_phoenix_tests(void);
int unicorn_on_the_cob_tests(void);
int black_knight_unicorn_tests(void);
int shark_with_a_horn_tests(void);
int shabby_the_narwhal_tests(void);
int narwhal_torpedo_tests(void);
int alluring_narwhal_tests(void);
int mermaid_unicorn_tests(void);
int classy_narwhal_tests(void);
int the_great_narwhal_tests(void);
