#pragma once
#include "gamemechanics.h"
#include "basedeck.h"
#include "gamephase.h"
#include "../resetfns.h"
#include <assert.h>

int rhinocorn_tests();
int extremely_fertile_unicorn_tests();
int magical_kittencorn_tests();
int stabby_the_unicorn_tests();
int puppicorn_tests();
int rainbow_unicorn_tests();
int zombie_unicorn_tests();
int extremely_destructive_unicorn_tests();
int chainsaw_unicorn_tests();
int llamacorn_tests();
int americorn_tests();
int ginormous_unicorn_tests();
int seductive_unicorn_tests();
int angel_unicorn_tests();
int queen_bee_unicorn_tests();
int greedy_flying_unicorn_tests();
int annoying_flying_unicorn_tests();
int magical_flying_unicorn_tests();
int swift_flying_unicorn_tests();
int majestic_flying_unicorn_tests();
int unicorn_phoenix_tests();
int unicorn_on_the_cob_tests();
int black_knight_unicorn_tests();
int shark_with_a_horn_tests();
int shabby_the_narwhal_tests();
int narwhal_torpedo_tests();
int alluring_narwhal_tests();
int mermaid_unicorn_tests();
int classy_narwhal_tests();
int the_great_narwhal_tests();
